package com.llchyan.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CAROUSAL".
 */
public class Carousal {

    private Integer carousal_id;
    private String title;
    private String address;
    private String category;
    private Integer sort;
    private String type;
    private String param;
    private java.util.Date date;

    public Carousal() {
    }

    public Carousal(Integer carousal_id) {
        this.carousal_id = carousal_id;
    }

    public Carousal(Integer carousal_id, String title, String address, String category, Integer sort, String type, String param, java.util.Date date) {
        this.carousal_id = carousal_id;
        this.title = title;
        this.address = address;
        this.category = category;
        this.sort = sort;
        this.type = type;
        this.param = param;
        this.date = date;
    }

    public Integer getCarousal_id() {
        return carousal_id;
    }

    public void setCarousal_id(Integer carousal_id) {
        this.carousal_id = carousal_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getParam() {
        return param;
    }

    public void setParam(String param) {
        this.param = param;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
