package com.llchyan.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.llchyan.bean.Note;
import com.llchyan.bean.Carousal;

import com.llchyan.dao.NoteDao;
import com.llchyan.dao.CarousalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig carousalDaoConfig;

    private final NoteDao noteDao;
    private final CarousalDao carousalDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        carousalDaoConfig = daoConfigMap.get(CarousalDao.class).clone();
        carousalDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        carousalDao = new CarousalDao(carousalDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Carousal.class, carousalDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        carousalDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public CarousalDao getCarousalDao() {
        return carousalDao;
    }

}
